apps:
  livecheck:
    command: 'bin/livecheck'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/livecheck/issues'
description: 'Tool to update ebuilds.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/livecheck/issues'
license: 'MIT'
name: 'livecheck'
parts:
  livecheck:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/livecheck'
summary: 'Tool to update ebuilds.'
title: 'livecheck'
version: '0.1.4'
website: 'https://tatsh.github.io/livecheck/'
